baseURL = "https://blog.starry-s.moe/"
defaultContentLanguage = "zh-cn"
# 网站语言, 仅在这里 CN 大写
languageCode = "zh-CN"
hasCJKLanguage = true
title = "STARRY-S' Blog"
theme = "LoveIt"

[params]
  version = "0.2.X"
  keywords = ["STARRY-S", "LoveIt", "Hugo", "Music", "Life"]

  # 页面头部导航栏配置
  [params.header]
    # ("fixed", "normal", "auto")
    desktopMode = "auto"
    mobileMode = "auto"
    [params.header.title]
      logo = ""
      name = "STARRY-S' Blog"
      pre = ""
      post = ""
      typeit = false

  [params.app]
    # 当添加到 iOS 主屏幕或者 Android 启动器时的标题, 覆盖默认标题
    title = "STARRY-S' Blog"
    # 是否隐藏网站图标资源链接
    noFavicon = false
    # 更现代的 SVG 网站图标, 可替代旧的 .png 和 .ico 文件
    # svgFavicon = ""
    # Android 浏览器主题色
    themeColor = "#ffffff"
    # Safari 图标颜色
    iconColor = "#5bbad5"
    # Windows v8-10磁贴颜色
    tileColor = "#da532c"

  # 搜索配置
  [params.search]
    enable = false
    # 搜索引擎的类型 ("lunr", "algolia")
    type = "lunr"
    # 文章内容最长索引长度
    contentLength = 4000
    # 搜索框的占位提示语
    placeholder = ""
    # 最大结果数目
    maxResultLength = 10
    # 结果内容片段长度
    snippetLength = 50
    # 搜索结果中高亮部分的 HTML 标签
    highlightTag = "em"
    # 是否在搜索索引中使用基于 baseURL 的绝对路径
    absoluteURL = false
    [params.search.algolia]
      index = ""
      appID = ""
      searchKey = ""

  # 页面底部信息配置
  [params.footer]
    enable = true
    custom = ''
    hugo = true
    copyright = true
    author = true
    # 网站创立年份
    since = 2016
    # 许可协议信息 (支持 HTML 格式)
    license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc-nd/4.0/" target="_blank">CC BY-NC-ND 4.0</a>'

  # Section (所有文章) 页面配置
  [params.section]
    # section 页面每页显示文章数量
    paginate = 20
    # 日期格式 (月和日)
    dateFormat = "01-02"
    # RSS 文章数目
    rss = 10

  # List (目录或标签) 页面配置
  [params.list]
    # list 页面每页显示文章数量
    paginate = 20
    # 日期格式 (月和日)
    dateFormat = "01-02"
    # RSS 文章数目
    rss = 10

  # 主页配置
  [params.home]
    # RSS 文章数目
    rss = 10
    # 主页个人信息
    [params.home.profile]
      enable = true
      gravatarEmail = ""
      avatarURL = "/images/avatar.jpg"
      title = "STARRY-S"
      subtitle = "Morning!"
      typeit = false
      social = true
      # 免责声明 (支持 HTML 格式)
      disclaimer = ""
  # 主页文章列表
  [params.home.posts]
    enable = true
    # 主页每页显示文章数量
    paginate = 6
  # 作者的社交信息设置
  [params.social]
    GitHub = "STARRY-S"
    Telegram = "STARRY-S"
    Weibo = "6990977018"
    Steam = "hxstarry-s"
    Bilibili = "19189337"
    Email = "hxstarrys@gmail.com"
    Twitter = "hxstarrys2022"
    RSS = true

  [params.page.comment]
    enable = true
    [params.page.comment.disqus]
      enable = true
      shortname = "starry-s-blog"

  # 网站验证代码
  [params.verification]
    google = ""
    bing = ""
    baidu = ""

  [params.seo]
    image = ""
    thumbnailUrl = ""

  [params.analytics]
    enable = true
    # Google Analytics
    [params.analytics.google]
      id = "G-70DHXLE02Z"
      anonymizeIP = true

  [params.cookieconsent]
    enable = false

  # mathjax
  [params.math]
    enable = true

  [params.page.code]
    copy = true
    maxShownLines = 9999

[author]
  name = "STARRY-S"
  email = "hxstarrys@gmail.com"
  link = "https://starry-s.moe"

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5


[markup]
  # (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false

[languages]
  # [languages.en]
  #   weight = 1
  #   title = "STARRY-S' Blog"
  #   languageCode = "en"
  #   languageName = "EN"
  #   hasCJKLanguage = true
  #   [[languages.en.menu.main]]
  #     identifier = "posts"
  #     pre = ""
  #     post = ""
  #     name = "Posts"
  #     url = "/posts/"
  #     title = ""
  #     weight = 1
  #   [[languages.en.menu.main]]
  #     identifier = "tags"
  #     pre = ""
  #     post = ""
  #     name = "Tags"
  #     url = "/tags/"
  #     title = ""
  #     weight = 2
  #   [[languages.en.menu.main]]
  #     identifier = "categories"
  #     pre = ""
  #     post = ""
  #     name = "Categories"
  #     url = "/categories/"
  #     title = ""
  #     weight = 3
  #   [[languages.en.menu.main]]
  #     identifier = "about"
  #     pre = ""
  #     post = ""
  #     name = "About"
  #     url = "/about/"
  #     title = ""
  #     weight = 4

  [languages.zh-cn]
    weight = 2
    title = "STARRY-S' Blog"
    languageCode = "zh-CN"
    languageName = "CN"
    hasCJKLanguage = true
    [[languages.zh-cn.menu.main]]
      identifier = "posts"
      pre = ""
      post = ""
      name = "文章"
      url = "/posts/"
      title = ""
      weight = 1
    [[languages.zh-cn.menu.main]]
      identifier = "tags"
      pre = ""
      post = ""
      name = "标签"
      url = "/tags/"
      title = ""
      weight = 2
    [[languages.zh-cn.menu.main]]
      identifier = "categories"
      pre = ""
      post = ""
      name = "分类"
      url = "/categories/"
      title = ""
      weight = 3
    [[languages.zh-cn.menu.main]]
      identifier = "about"
      pre = ""
      post = ""
      name = "关于"
      url = "/about/"
      title = ""
      weight = 4
